services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/templates:ro
      - letsencrypt:/etc/letsencrypt:ro
      - certbot:/usr/share/nginx/html:ro
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    env_file:
      - .env
    command: >-
      certonly --reinstall --webroot --webroot-path=/usr/share/nginx/html
      --email ${EMAIL} --agree-tos --no-eff-email
      -d ${DOMAIN}
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot:/usr/share/nginx/html

volumes:
  letsencrypt:
  certbot:
